# Generated by Django 5.0 on 2023-12-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'catogories'},
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='categoty',
            new_name='category',
        ),
    ]
